import { Appointment, BusinessStats } from "./types";

export const initialAppointments: Appointment[] = [
  {
    id: "cs-101",
    clientName: "Benjamin Miller",
    phone: "5512345678",
    email: "benjamin.miller@example.com",
    service: "Consulta General",
    date: "2026-07-04",
    time: "10:30 AM",
    amount: 500,
    paymentMethod: "Tarjeta",
    paymentStatus: "Confirmado",
    absences: 0,
    receiptStatus: "NONE",
  },
  {
    id: "cs-102",
    clientName: "Sarah Jenkins",
    phone: "5523456789",
    email: "sarah.jenkins@example.com",
    service: "Fisioterapia",
    date: "2026-07-04",
    time: "02:15 PM",
    amount: 800,
    paymentMethod: "OXXO",
    paymentStatus: "Por Verificar",
    absences: 2,
    receiptStatus: "PENDIENTE",
  },
  {
    id: "cs-103",
    clientName: "David Thompson",
    phone: "5534567890",
    email: "david.thompson@example.com",
    service: "Revisión Financiera",
    date: "2026-07-04",
    time: "09:00 AM",
    amount: 1200,
    paymentMethod: "OXXO",
    paymentStatus: "Por Verificar",
    absences: 3,
    receiptStatus: "PENDIENTE",
  },
  {
    id: "cs-104",
    clientName: "Elena Rodriguez",
    phone: "5545678901",
    email: "elena.rodriguez@example.com",
    service: "Consulta General",
    date: "2026-07-03",
    time: "11:00 AM",
    amount: 500,
    paymentMethod: "Tarjeta",
    paymentStatus: "Confirmado",
    absences: 0,
    receiptStatus: "NONE",
  },
  {
    id: "cs-105",
    clientName: "Marcus Wu",
    phone: "5556789012",
    email: "marcus.wu@example.com",
    service: "Seguimiento",
    date: "2026-07-04",
    time: "04:00 PM",
    amount: 400,
    paymentMethod: "Tarjeta",
    paymentStatus: "Confirmado",
    absences: 0,
    receiptStatus: "NONE",
  },
];

export const initialStats: BusinessStats = {
  attendanceRate: 85,
  confirmedCount: 124,
  rescheduledCount: 12,
};

export const SERVICES = [
  { name: "Consulta General", price: 500, duration: "30 min" },
  { name: "Fisioterapia", price: 800, duration: "60 min" },
  { name: "Revisión Financiera", price: 1200, duration: "45 min" },
  { name: "Seguimiento", price: 400, duration: "15 min" },
];
